<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keyEquivalent</key>
	<string>^~F</string>
	<key>name</key>
	<string>Fenced Markdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(((`|\~){3,5})(?!\3))[ \t]*(?:(\{?)[ \t]*(?i)(bash|sh|zshcss|diff|html|xhtml|javascript|js|node|json|perl|php|python|py|xml|rss|xsd|wsdl|ApacheConf|apache|applescript|C|C\+\+|cpp|c#|csharp|ruby|rake|rb|rbx|makefile|mak|markdown|clojure|ini|java|batchfile|bat|batch|dosbatch|erlang|trex)[ \t]*(\}?)[ \t]*)?$</string>
					<key>captures</key>
					<dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.language.markdown.fenced</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(\2)(?!\3)</string>
					<key>name</key>
					<string>markup.raw.block.markdown.fenced</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.markdown.fenced</string>
	<key>uuid</key>
	<string>F5E04BF4-69A9-45AE-9205-B3F3C2B00130</string>
</dict>
</plist>
