<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Github Flavored Markdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.markdown.fenced</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)^
				(?=	[ ]{,3}&gt;.
				|	([ ]{4}|\t)(?!$)
				|	[#]{1,6}\s*+
				|	[ ]{,3}(?&lt;marker&gt;[-*_])([ ]{,2}\k&lt;marker&gt;){2,}[ \t]*+$
				)</string>
			<key>comment</key>
			<string>
				We could also use an empty end match and set
				applyEndPatternLast, but then we must be sure that the begin
				pattern will only match stuff matched by the sub-patterns.
			</string>
			<key>end</key>
			<string>(?x)^
				(?!	[ ]{,3}&gt;.
				|	([ ]{4}|\t)
				|	[#]{1,6}\s*+
				|	[ ]{,3}(?&lt;marker&gt;[-*_])([ ]{,2}\k&lt;marker&gt;){2,}[ \t]*+$
				)</string>
			<key>name</key>
			<string>meta.block-level.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[ ]{0,3}([*+-])(?=\s)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.markdown.github</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=\S)</string>
			<key>name</key>
			<string>markup.list.unnumbered.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list-paragraph</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[ ]{0,3}[0-9]+(\.)(?=\s)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.markdown.github</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=\S)</string>
			<key>name</key>
			<string>markup.list.numbered.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list-paragraph</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=&lt;(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b)(?!.*?&lt;/\1&gt;)</string>
			<key>comment</key>
			<string>
				Markdown formatting is disabled inside block-level tags.
			</string>
			<key>end</key>
			<string>(?&lt;=^&lt;/\1&gt;$\n)</string>
			<key>name</key>
			<string>meta.disable-markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=&lt;(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b)</string>
			<key>comment</key>
			<string>Same rule but for one line disables.</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>meta.disable-markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.markdown.github</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown.github</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown.github</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown.github</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.markdown.github</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.markdown.github</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown.github</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown.github</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x:
				\s*						# Leading whitespace
				(\[)(.+?)(\])(:)		# Reference name
				[ \t]*					# Optional whitespace
				(&lt;?)(\S+?)(&gt;?)			# The url
				[ \t]*					# Optional whitespace
				(?:
					  ((\().+?(\)))		# Match title in quotes…
					| ((").+?("))		# or in parens.
				)?						# Title is optional
				\s*						# Optional whitespace
				$
			)</string>
			<key>name</key>
			<string>meta.link.reference.def.markdown.github</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=\S)(?![=-]{3,}(?=$))</string>
			<key>end</key>
			<string>^(?:\s*$|(?=[ ]{,3}&gt;.))|(?=[ \t]*\n)(?&lt;=^===|^====|=====|^---|^----|-----)[ \t]*\n|(?=^#)|(?=^```)</string>
			<key>name</key>
			<string>meta.paragraph.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown.github</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(={3,})(?=[ \t]*$)</string>
					<key>name</key>
					<string>markup.heading.1.markdown.github</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown.github</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(-{3,})(?=[ \t]*$)</string>
					<key>name</key>
					<string>markup.heading.2.markdown.github</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ampersand</key>
		<dict>
			<key>comment</key>
			<string>
				Markdown will convert this for us. We match it so that the
				HTML grammar will not mark it up as invalid.
			</string>
			<key>match</key>
			<string>&amp;(?!([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+);)</string>
			<key>name</key>
			<string>meta.other.valid-ampersand.markdown.github</string>
		</dict>
		<key>block_quote</key>
		<dict>
			<key>begin</key>
			<string>\G[ ]{,3}(&gt;)(?!$)[ ]?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.blockquote.markdown.github</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>
				We terminate the block quote when seeing an empty line, a
				separator or a line with leading &gt; characters. The latter is
				to “reset” the quote level for quoted lines.
			</string>
			<key>end</key>
			<string>(?x)^
				(?=	\s*$
				|	[ ]{,3}(?&lt;marker&gt;[-*_])([ ]{,2}\k&lt;marker&gt;){2,}[ \t]*+$
				|	[ ]{,3}&gt;.
				)</string>
			<key>name</key>
			<string>markup.quote.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x)\G
						(?=	[ ]{,3}&gt;.
						)</string>
					<key>end</key>
					<string>^</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block_quote</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?x)\G
						(?=	([ ]{4}|\t)
						|	[#]{1,6}\s*+
						|	[ ]{,3}(?&lt;marker&gt;[-*_])([ ]{,2}\k&lt;marker&gt;){2,}[ \t]*+$
						)</string>
					<key>end</key>
					<string>^</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block_raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#heading</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#separator</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)\G
						(?!	$
						|	[ ]{,3}&gt;.
						|	([ ]{4}|\t)
						|	[#]{1,6}\s*+
						|	[ ]{,3}(?&lt;marker&gt;[-*_])([ ]{,2}\k&lt;marker&gt;){2,}[ \t]*+$
						)</string>
					<key>end</key>
					<string>$|(?&lt;=\n)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>block_raw</key>
		<dict>
			<key>match</key>
			<string>\G([ ]{4}|\t).*$\n?</string>
			<key>name</key>
			<string>markup.raw.block.markdown.github</string>
		</dict>
		<key>emoji</key>
		<dict>
			<key>match</key>
			<string>(?x)
			:(
			    \+1|\-1|100|1234|8ball|a|ab|abc|abcd|accept|aerial\_tramway|airplane|alarm\_clock|alien|ambulance|anchor|angel
			    |anger|angry|anguished|ant|apple|aquarius|aries|arrow\_backward|arrow\_double\_down|arrow\_double\_up
			    |arrow\_down|arrow\_down\_small|arrow\_forward|arrow\_heading\_down|arrow\_heading\_up|arrow\_left
			    |arrow\_lower\_left|arrow\_lower\_right|arrow\_right|arrow\_right\_hook|arrow\_up|arrow\_up\_down
			    |arrow\_up\_small|arrow\_upper\_left|arrow\_upper\_right|arrows\_clockwise|arrows\_counterclockwise|art
			    |articulated\_lorry|astonished|athletic\_shoe|atm|b|baby|baby\_bottle|baby\_chick|baby\_symbol|back
			    |baggage\_claim|balloon|ballot\_box\_with\_check|bamboo|banana|bangbang|bank|bar\_chart|barber|baseball
			    |basketball|bath|bathtub|battery|bear|bee|beer|beers|beetle|beginner|bell|bento|bicyclist|bike|bikini|bird
			    |birthday|black\_circle|black\_joker|black\_large\_square|black\_medium\_small\_square|black\_medium\_square
			    |black\_nib|black\_small\_square|black\_square\_button|blossom|blowfish|blue\_book|blue\_car|blue\_heart|blush
			    |boar|boat|bomb|book|bookmark|bookmark\_tabs|books|boom|boot|bouquet|bow|bowling|bowtie|boy|bread
			    |bride\_with\_veil|bridge\_at\_night|briefcase|broken\_heart|bug|bulb|bullettrain\_front|bullettrain\_side|bus
			    |busstop|bust\_in\_silhouette|busts\_in\_silhouette|cactus|cake|calendar|calling|camel|camera|cancer|candy
			    |capital\_abcd|capricorn|car|card\_index|carousel\_horse|cat|cat2|cd|chart|chart\_with\_downwards\_trend
			    |chart\_with\_upwards\_trend|checkered\_flag|cherries|cherry\_blossom|chestnut|chicken|children\_crossing
			    |chocolate\_bar|christmas\_tree|church|cinema|circus\_tent|city\_sunrise|city\_sunset|cl|clap|clapper
			    |clipboard|clock1|clock10|clock1030|clock11|clock1130|clock12|clock1230|clock130|clock2|clock230|clock3
			    |clock330|clock4|clock430|clock5|clock530|clock6|clock630|clock7|clock730|clock8|clock830|clock9|clock930
			    |closed\_book|closed\_lock\_with\_key|closed\_umbrella|cloud|clubs|cn|cocktail|coffee|cold\_sweat|collision
			    |computer|confetti\_ball|confounded|confused|congratulations|construction|construction\_worker
			    |convenience\_store|cookie|cool|cop|copyright|corn|couple|couple\_with\_heart|couplekiss|cow|cow2|credit\_card
			    |crescent\_moon|crocodile|crossed\_flags|crown|cry|crying\_cat\_face|crystal\_ball|cupid|curly\_loop
			    |currency\_exchange|curry|custard|customs|cyclone|dancer|dancers|dango|dart|dash|date|de|deciduous\_tree
			    |department\_store|diamond\_shape\_with\_a\_dot\_inside|diamonds|disappointed|disappointed\_relieved|dizzy
			    |dizzy\_face|do\_not\_litter|dog|dog2|dollar|dolls|dolphin|door|doughnut|dragon|dragon\_face|dress
			    |dromedary\_camel|droplet|dvd|e\-mail|ear|ear\_of\_rice|earth\_africa|earth\_americas|earth\_asia|egg|eggplant
			    |eight|eight\_pointed\_black\_star|eight\_spoked\_asterisk|electric\_plug|elephant|email|end|envelope
			    |envelope\_with\_arrow|es|euro|european\_castle|european\_post\_office|evergreen\_tree|exclamation
			    |expressionless|eyeglasses|eyes|facepunch|factory|fallen\_leaf|family|fast\_forward|fax|fearful|feelsgood|feet
			    |ferris\_wheel|file\_folder|finnadie|fire|fire\_engine|fireworks|first\_quarter\_moon
			    |first\_quarter\_moon\_with\_face|fish|fish\_cake|fishing\_pole\_and\_fish|fist|five|flags|flashlight|flipper
			    |floppy\_disk|flower\_playing\_cards|flushed|foggy|football|footprints|fork\_and\_knife|fountain|four
			    |four\_leaf\_clover|fr|free|fried\_shrimp|fries|frog|frowning|fu|fuelpump|full\_moon|full\_moon\_with\_face
			    |game\_die|gb|gem|gemini|ghost|gift|gift\_heart|girl|globe\_with\_meridians|goat|goberserk|godmode|golf|grapes
			    |green\_apple|green\_book|green\_heart|grey\_exclamation|grey\_question|grimacing|grin|grinning|guardsman
			    |guitar|gun|haircut|hamburger|hammer|hamster|hand|handbag|hankey|hash|hatched\_chick|hatching\_chick
			    |headphones|hear\_no\_evil|heart|heart\_decoration|heart\_eyes|heart\_eyes\_cat|heartbeat|heartpulse|hearts
			    |heavy\_check\_mark|heavy\_division\_sign|heavy\_dollar\_sign|heavy\_exclamation\_mark|heavy\_minus\_sign
			    |heavy\_multiplication\_x|heavy\_plus\_sign|helicopter|herb|hibiscus|high\_brightness|high\_heel|hocho
			    |honey\_pot|honeybee|horse|horse\_racing|hospital|hotel|hotsprings|hourglass|hourglass\_flowing\_sand|house
			    |house\_with\_garden|hurtrealbad|hushed|ice\_cream|icecream|id|ideograph\_advantage|imp|inbox\_tray
			    |incoming\_envelope|information\_desk\_person|information\_source|innocent|interrobang|iphone|it
			    |izakaya\_lantern|jack\_o\_lantern|japan|japanese\_castle|japanese\_goblin|japanese\_ogre|jeans|joy|joy\_cat
			    |jp|key|keycap\_ten|kimono|kiss|kissing|kissing\_cat|kissing\_closed\_eyes|kissing\_heart
			    |kissing\_smiling\_eyes|knife|koala|koko|kr|lantern|large\_blue\_circle|large\_blue\_diamond
			    |large\_orange\_diamond|last\_quarter\_moon|last\_quarter\_moon\_with\_face|laughing|leaves|ledger
			    |left\_luggage|left\_right\_arrow|leftwards\_arrow\_with\_hook|lemon|leo|leopard|libra|light\_rail|link|lips
			    |lipstick|lock|lock\_with\_ink\_pen|lollipop|loop|loud\_sound|loudspeaker|love\_hotel|love\_letter
			    |low\_brightness|m|mag|mag\_right|mahjong|mailbox|mailbox\_closed|mailbox\_with\_mail|mailbox\_with\_no\_mail
			    |man|man\_with\_gua\_pi\_mao|man\_with\_turban|mans\_shoe|maple\_leaf|mask|massage|meat\_on\_bone|mega|melon
			    |memo|mens|metal|metro|microphone|microscope|milky\_way|minibus|minidisc|mobile\_phone\_off|money\_with\_wings
			    |moneybag|monkey|monkey\_face|monorail|moon|mortar\_board|mount\_fuji|mountain\_bicyclist|mountain\_cableway
			    |mountain\_railway|mouse|mouse2|movie\_camera|moyai|muscle|mushroom|musical\_keyboard|musical\_note
			    |musical\_score|mute|nail\_care|name\_badge|neckbeard|necktie|negative\_squared\_cross\_mark|neutral\_face|new
			    |new\_moon|new\_moon\_with\_face|newspaper|ng|night\_with\_stars|nine|no\_bell|no\_bicycles|no\_entry
			    |no\_entry\_sign|no\_good|no\_mobile\_phones|no\_mouth|no\_pedestrians|no\_smoking|non\-potable\_water|nose
			    |notebook|notebook\_with\_decorative\_cover|notes|nut\_and\_bolt|o|o2|ocean|octocat|octopus|oden|office|ok
			    |ok\_hand|ok\_woman|older\_man|older\_woman|on|oncoming\_automobile|oncoming\_bus|oncoming\_police\_car
			    |oncoming\_taxi|one|open\_book|open\_file\_folder|open\_hands|open\_mouth|ophiuchus|orange\_book|outbox\_tray
			    |ox|package|page\_facing\_up|page\_with\_curl|pager|palm\_tree|panda\_face|paperclip|parking
			    |part\_alternation\_mark|partly\_sunny|passport\_control|paw\_prints|peach|pear|pencil|pencil2|penguin|pensive
			    |performing\_arts|persevere|person\_frowning|person\_with\_blond\_hair|person\_with\_pouting\_face|phone|pig
			    |pig2|pig\_nose|pill|pineapple|pisces|pizza|point\_down|point\_left|point\_right|point\_up|point\_up\_2
			    |police\_car|poodle|poop|post\_office|postal\_horn|postbox|potable\_water|pouch|poultry\_leg|pound
			    |pouting\_cat|pray|princess|punch|purple\_heart|purse|pushpin|put\_litter\_in\_its\_place|question|rabbit
			    |rabbit2|racehorse|radio|radio\_button|rage|rage1|rage2|rage3|rage4|railway\_car|rainbow|raised\_hand
			    |raised\_hands|raising\_hand|ram|ramen|rat|recycle|red\_car|red\_circle|registered|relaxed|relieved|repeat
			    |repeat\_one|restroom|revolving\_hearts|rewind|ribbon|rice|rice\_ball|rice\_cracker|rice\_scene|ring|rocket
			    |roller\_coaster|rooster|rose|rotating\_light|round\_pushpin|rowboat|ru|rugby\_football|runner|running
			    |running\_shirt\_with\_sash|sa|sagittarius|sailboat|sake|sandal|santa|satellite|satisfied|saxophone|school
			    |school\_satchel|scissors|scorpius|scream|scream\_cat|scroll|seat|secret|see\_no\_evil|seedling|seven
			    |shaved\_ice|sheep|shell|ship|shipit|shirt|shit|shoe|shower|signal\_strength|six|six\_pointed\_star|ski|skull
			    |sleeping|sleepy|slot\_machine|small\_blue\_diamond|small\_orange\_diamond|small\_red\_triangle
			    |small\_red\_triangle\_down|smile|smile\_cat|smiley|smiley\_cat|smiling\_imp|smirk|smirk\_cat|smoking|snail
			    |snake|snowboarder|snowflake|snowman|sob|soccer|soon|sos|sound|space\_invader|spades|spaghetti|sparkle
			    |sparkler|sparkles|sparkling\_heart|speak\_no\_evil|speaker|speech\_balloon|speedboat|squirrel|star|star2
			    |stars|station|statue\_of\_liberty|steam\_locomotive|stew|straight\_ruler|strawberry|stuck\_out\_tongue
			    |stuck\_out\_tongue\_closed\_eyes|stuck\_out\_tongue\_winking\_eye|sun\_with\_face|sunflower|sunglasses|sunny
			    |sunrise|sunrise\_over\_mountains|surfer|sushi|suspect|suspension\_railway|sweat|sweat\_drops|sweat\_smile
			    |sweet\_potato|swimmer|symbols|syringe|tada|tanabata\_tree|tangerine|taurus|taxi|tea|telephone
			    |telephone\_receiver|telescope|tennis|tent|thought\_balloon|three|thumbsdown|thumbsup|ticket|tiger|tiger2
			    |tired\_face|tm|toilet|tokyo\_tower|tomato|tongue|top|tophat|tractor|traffic\_light|train|train2|tram
			    |triangular\_flag\_on\_post|triangular\_ruler|trident|triumph|trolleybus|trollface|trophy|tropical\_drink
			    |tropical\_fish|truck|trumpet|tshirt|tulip|turtle|tv|twisted\_rightwards\_arrows|two|two\_hearts
			    |two\_men\_holding\_hands|two\_women\_holding\_hands|u5272|u5408|u55b6|u6307|u6708|u6709|u6e80|u7121|u7533
			    |u7981|u7a7a|uk|umbrella|unamused|underage|unlock|up|us|v|vertical\_traffic\_light|vhs|vibration\_mode
			    |video\_camera|video\_game|violin|virgo|volcano|vs|walking|waning\_crescent\_moon|waning\_gibbous\_moon
			    |warning|watch|water\_buffalo|watermelon|wave|wavy\_dash|waxing\_crescent\_moon|waxing\_gibbous\_moon|wc|weary
			    |wedding|whale|whale2|wheelchair|white\_check\_mark|white\_circle|white\_flower|white\_large\_square
			    |white\_medium\_small\_square|white\_medium\_square|white\_small\_square|white\_square\_button|wind\_chime
			    |wine\_glass|wink|wolf|woman|womans\_clothes|womans\_hat|womens|worried|wrench|x|yellow\_heart|yen|yum|zap
			    |zero|zzz
			):
		    </string>
			<key>name</key>
			<string>markup.emoji.markdown.github</string>
		</dict>
		<key>strike</key>
		<dict>
			<key>begin</key>
			<string>(?x)
						(?&lt;=[^a-zA-Z\d]|^)(~~)(?=\S)								# Open
						(?=
							(
							    &lt;[^&gt;]*+&gt;							# HTML tags
							  | (?&lt;raw&gt;`+)([^`]|(?!(?&lt;!`)\k&lt;raw&gt;(?!`))`)*+\k&lt;raw&gt;
																	# Raw
							  | \\[\\`*_{}\[\]()#.!+\-&gt;]?+			# Escapes
							  | \[
								(				
								        (?&lt;square&gt;					# Named group
											[^\[\]\\]				# Match most chars
								          | \\.						# Escaped chars
								          | \[ \g&lt;square&gt;*+ \]		# Nested brackets
								        )*+
									\]
									(
										(							# Reference Link
											[ ]?					# Optional space
											\[[^\]]*+\]				# Ref name
										)
									  | (							# Inline Link
											\(						# Opening paren
												[ \t]*+				# Optional whtiespace
												&lt;?(.*?)&gt;?			# URL
												[ \t]*+				# Optional whtiespace
												(					# Optional Title
													(?&lt;title&gt;['"])
													(.*?)
													\k&lt;title&gt;
												)?
											\)
										)
									)
								)
							| (?!(?&lt;=\S)\1).						# Everything besides
																	# style closer
							)++
							(?&lt;=\S)\1								# Close
						)
					</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.strikethrough.markdown.github</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)(\1)(?![a-zA-Z\d])</string>
			<key>name</key>
			<string>markup.strikethrough.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?=&lt;[^&gt;]*?&gt;)</string>
					<key>end</key>
					<string>(?&lt;=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#emoji</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#autolink</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#autolink-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
			</array>
		</dict>
		<key>bold</key>
		<dict>
			<key>begin</key>
			<string>(?x)
						(?&lt;=[^a-zA-z\d]|^)(\*\*|__)(?=\S)								# Open
						(?=
							(
							    &lt;[^&gt;]*+&gt;							# HTML tags
							  | (?&lt;raw&gt;`+)([^`]|(?!(?&lt;!`)\k&lt;raw&gt;(?!`))`)*+\k&lt;raw&gt;
																	# Raw
							  | \\[\\`*_{}\[\]()#.!+\-&gt;]?+			# Escapes
							  | \[
								(				
								        (?&lt;square&gt;					# Named group
											[^\[\]\\]				# Match most chars
								          | \\.						# Escaped chars
								          | \[ \g&lt;square&gt;*+ \]		# Nested brackets
								        )*+
									\]
									(
										(							# Reference Link
											[ ]?					# Optional space
											\[[^\]]*+\]				# Ref name
										)
									  | (							# Inline Link
											\(						# Opening paren
												[ \t]*+				# Optional whtiespace
												&lt;?(.*?)&gt;?			# URL
												[ \t]*+				# Optional whtiespace
												(					# Optional Title
													(?&lt;title&gt;['"])
													(.*?)
													\k&lt;title&gt;
												)?
											\)
										)
									)
								)
							| (?!(?&lt;=\S)\1).						# Everything besides
																	# style closer
							)++
							(?&lt;=\S)\1								# Close
						)
					</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.markdown.github</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)(\1)(?![a-zA-z\d])</string>
			<key>name</key>
			<string>markup.bold.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?=&lt;[^&gt;]*?&gt;)</string>
					<key>end</key>
					<string>(?&lt;=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#emoji</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strike</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#autolink</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#autolink-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
			</array>
		</dict>
		<key>bracket</key>
		<dict>
			<key>comment</key>
			<string>
				Markdown will convert this for us. We match it so that the
				HTML grammar will not mark it up as invalid.
			</string>
			<key>match</key>
			<string>&lt;(?![a-z/?\$!])</string>
			<key>name</key>
			<string>meta.other.valid-bracket.markdown.github</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\[-`*_#+.!(){}\[\]\\&gt;]</string>
			<key>name</key>
			<string>constant.character.escape.markdown.github</string>
		</dict>
		<key>heading</key>
		<dict>
			<key>begin</key>
			<string>\G(#{1,6})(?!#)\s*(?=\S)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.markdown.github</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.section.markdown.github</string>
			<key>end</key>
			<string>\s*(#*)$\n?</string>
			<key>name</key>
			<string>markup.heading.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>image-inline</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown.github</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.markdown.github</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.markdown.github</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown.github</string>
				</dict>
				<key>14</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.markdown.github</string>
				</dict>
				<key>15</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.markdown.github</string>
				</dict>
				<key>16</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.markdown.github</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown.github</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.whitespace.markdown.github</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown.github</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.image.markdown.github</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x:
				\!							# Images start with !
				(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])	
											# Match the link text.
				([ ])?						# Space not allowed
				(\()						# Opening paren for url
					(&lt;?)(\S+?)(&gt;?)			# The url
					[ \t]*					# Optional whitespace
					(?:
						  ((\().+?(\)))		# Match title in parens…
						| ((").+?("))		# or in quotes.
					)?						# Title is optional
					\s*						# Optional whitespace
				(\))
			 )</string>
			<key>name</key>
			<string>meta.image.inline.markdown.github</string>
		</dict>
		<key>image-ref</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.markdown.github</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.markdown.github</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown.github</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\!(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])[ ]?(\[)(.*?)(\])</string>
			<key>name</key>
			<string>meta.image.reference.markdown.github</string>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#emoji</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strike</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-break</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#autolink</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#autolink-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
			</array>
		</dict>
		<key>italic</key>
		<dict>
			<key>begin</key>
			<string>(?x)
						(?&lt;=[^a-zA-Z\d]|^)(\*|_)(?=\S)								# Open
						(?=
							(
							    &lt;[^&gt;]*+&gt;							# HTML tags
							  | (?&lt;raw&gt;`+)([^`]|(?!(?&lt;!`)\k&lt;raw&gt;(?!`))`)*+\k&lt;raw&gt;
																	# Raw
							  | \\[\\`*_{}\[\]()#.!+\-&gt;]?+			# Escapes
							  | \[
								(				
								        (?&lt;square&gt;					# Named group
											[^\[\]\\]				# Match most chars
								          | \\.						# Escaped chars
								          | \[ \g&lt;square&gt;*+ \]		# Nested brackets
								        )*+
									\]
									(
										(							# Reference Link
											[ ]?					# Optional space
											\[[^\]]*+\]				# Ref name
										)
									  | (							# Inline Link
											\(						# Opening paren
												[ \t]*+				# Optional whtiespace
												&lt;?(.*?)&gt;?			# URL
												[ \t]*+				# Optional whtiespace
												(					# Optional Title
													(?&lt;title&gt;['"])
													(.*?)
													\k&lt;title&gt;
												)?
											\)
										)
									)
								)
							  | \1\1								# Must be bold closer
							  | (?!(?&lt;=\S)\1).						# Everything besides
																	# style closer
							)++
							(?&lt;=\S)\1								# Close
						)
					</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.italic.markdown.github</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)(\1)((?!\1)|(?=\1\1))(?![a-zA-Z\d])</string>
			<key>name</key>
			<string>markup.italic.markdown.github</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?=&lt;[^&gt;]*?&gt;)</string>
					<key>end</key>
					<string>(?&lt;=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#emoji</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strike</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#autolink</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#autolink-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
			</array>
		</dict>
		<key>line-break</key>
		<dict>
			<key>match</key>
			<string> {2,}$</string>
			<key>name</key>
			<string>meta.dummy.line-break</string>
		</dict>
		<key>link-email</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown.github</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;)((?:mailto:)?[-.\w]+@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+)(&gt;)</string>
			<key>name</key>
			<string>meta.link.email.lt-gt.markdown.github</string>
		</dict>
		<key>link-inet</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown.github</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;)((?:https?|ftp)://.*?)(&gt;)</string>
			<key>name</key>
			<string>meta.link.inet.markdown.github</string>
		</dict>
		<key>autolink</key>
		<dict>
			<key>match</key>
			<string>(?x)(?i)
			\b(?:
				(?:ht|f)tps?://(?:(?:[a-z\d\-_]+(?:\.[a-z\d\-._]+)+)|localhost)|
				(w{3}\.)[a-z\d\-_]+(?:\.[a-z\d\-._]+)+
			)
			/?[a-z\d\-._(){}\[\]?,!'/+&amp;@%$#=:"|~;]*
			[a-z\d\-_~/#@$*+=]
			</string>
			<key>name</key>
			<string>markup.underline.link.markdown.github</string>
		</dict>
		<key>autolink-email</key>
		<dict>
			<key>match</key>
			<string>(?i)((?:[\-+\w]([\w\-+]|\.(?!\.))+)@(?:[\w\-]+\.)(([\w\-]|(?&lt;!\.)\.(?!\.))*)[a-z](?![\d\-_@]))</string>
			<key>name</key>
			<string>markup.underline.link.email.markdown.github</string>
		</dict>
		<key>link-inline</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown.github</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown.github</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown.github</string>
				</dict>
				<key>14</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>15</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown.github</string>
				</dict>
				<key>16</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown.github</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown.github</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.whitespace.markdown.github</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown.github</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown.github</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x:
				(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])	
											# Match the link text.
				([ ])?						# Space not allowed
				(\()						# Opening paren for url
					(&lt;?)(.*?)(&gt;?)			# The url
					[ \t]*					# Optional whitespace
					(?:
						  ((\().+?(\)))		# Match title in parens…
						| ((").+?("))		# or in quotes.
					)?						# Title is optional
					\s*						# Optional whitespace
				(\))
			 )</string>
			<key>name</key>
			<string>meta.link.inline.markdown.github</string>
		</dict>
		<key>link-ref</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown.github</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown.github</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown.github</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown.github</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])[ ]?(\[)([^\]]*+)(\])</string>
			<key>name</key>
			<string>meta.link.reference.markdown.github</string>
		</dict>
		<key>link-ref-literal</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown.github</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown.github</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown.github</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown.github</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])[ ]?(\[)(\])</string>
			<key>name</key>
			<string>meta.link.reference.literal.markdown.github</string>
		</dict>
		<key>list-paragraph</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G\s+(?=\S)</string>
					<key>end</key>
					<string>^\s*$</string>
					<key>name</key>
					<string>meta.paragraph.list.markdown.github</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>raw</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.markdown.github</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.markdown.github</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(`+)([^`]|(?!(?&lt;!`)\1(?!`))`)*+(\1)</string>
			<key>name</key>
			<string>markup.raw.inline.markdown.github</string>
		</dict>
		<key>separator</key>
		<dict>
			<key>match</key>
			<string>\G[ ]{,3}([-*_])([ ]{,2}\1){2,}[ \t]*$\n?</string>
			<key>name</key>
			<string>meta.separator.markdown.github</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.markdown.github</string>
	<key>uuid</key>
	<string>0A1D9874-B448-11D9-BD50-000D93B6E43C</string>
</dict>
</plist>
