<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>firstLineMatch</key>
	<string>^Format:\s*(?i:complete)\s*$</string>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>MultiMarkdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^([A-Za-z0-9]+)(:)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.multimarkdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$|^(?=[A-Za-z0-9]+:)</string>
			<key>name</key>
			<string>meta.header.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>The reason for not setting scopeName = "string.unquoted" 
						(for the parent rule) is that we do not want
						newlines to be marked as string.unquoted</string>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>string.unquoted.multimarkdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?!=[A-Za-z0-9]+:)</string>
			<key>end</key>
			<string>^(?=not)possible$</string>
			<key>name</key>
			<string>meta.content.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#raw-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>raw-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^`````</string>
					<key>end</key>
					<string>^`````</string>
					<key>name</key>
					<string>markup.raw.block.multimarkdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#fenced-blocks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^````</string>
					<key>end</key>
					<string>^````</string>
					<key>name</key>
					<string>markup.raw.block.multimarkdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#fenced-blocks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^```</string>
					<key>end</key>
					<string>^```</string>
					<key>name</key>
					<string>markup.raw.block.multimarkdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#fenced-blocks</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>fenced-blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#fenced-js</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-json</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-py</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-xml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-php</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-diff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-perl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-bash</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-apacheconf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-applescript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-cpp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-csharp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-makefile</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-markdown</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-clojure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-ini</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-java</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced-batchfile</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.plain</string>
				</dict>
			</array>
		</dict>
		<key>fenced-bash</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(bash|sh|zsh)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-bash.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<key>fenced-css</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(css)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-css.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<key>fenced-diff</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(diff)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-diff.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.diff</string>
				</dict>
			</array>
		</dict>
		<key>fenced-html</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(html|xhtml)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-html.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<key>fenced-js</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(javascript|js|node)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-javascript.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>fenced-json</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(json)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-json.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<key>fenced-perl</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(perl)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-perl.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<key>fenced-php</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(php)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-php.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
			</array>
		</dict>
		<key>fenced-py</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(python|py)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-python.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>fenced-xml</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(xml|rss|xsd|wsdl)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-xml.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<key>fenced-apacheconf</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(ApacheConf|apache)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-apacheconf.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.apacheconf</string>
				</dict>
			</array>
		</dict>
		<key>fenced-applescript</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(applescript)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-applescript.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.applescript</string>
				</dict>
			</array>
		</dict>
		<key>fenced-cpp</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(C|C\+\+|cpp)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-cpp.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c, source.c++</string>
				</dict>
			</array>
		</dict>
		<key>fenced-csharp</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(c#|csharp)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-csharp.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
		</dict>
		<key>fenced-ruby</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(ruby|rake|rb|rbx)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-ruby.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<key>fenced-makefile</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(makefile|mak)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-makefile.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.makefile</string>
				</dict>
			</array>
		</dict>
		<key>fenced-markdown</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(markdown)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-markdown.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.multimarkdown</string>
				</dict>
			</array>
		</dict>
		<key>fenced-clojure</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(clojure)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-clojure.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.clojure</string>
				</dict>
			</array>
		</dict>
		<key>fenced-ini</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(ini)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-ini.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ini</string>
				</dict>
			</array>
		</dict>
		<key>fenced-java</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(java)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-java.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<key>fenced-batchfile</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=```)[ \t]*(?i)(batchfile|bat|batch|dosbatch)[ \t]*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=```)</string>
			<key>name</key>
			<string>markup.fenced.embedded-batchfile.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.dosbatch</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.markdown.multimarkdown</string>
	<key>uuid</key>
	<string>F5E04BF4-69A9-45AE-9205-B3F3C2B00130</string>
</dict>
</plist>
